language: python
python:
  - '3.9'

branches:
  only:
    - main

before_script:
  - cd pur_beurre_app
  - python -m venv env
  - source env/bin/activate
  - pip install -r requirements.txt --use-pep517 
  - python manage.py collectstatic

services:
    - postgresql

script:
  - pytest
